FROM openjdk:latest

COPY . .

COPY maven-jar-fire-sensor-jar-with-dependencies.jar maven-jar-fire-sensor-jar-with-dependencies.jar
CMD ["java", "-jar", "maven-jar-fire-sensor-jar-with-dependencies.jar"]